language: ruby
services:
- docker
before_install:
- docker build -t keyerd/tests:go-helloworld .
- docker run -d -p 3030:8080 --name  go-helloworld keyerd/tests:go-helloworld
- docker exec -it go-helloworld /bin/sh -c "cd tests; go test"
script:
- docker ps | grep -q go-helloworld
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  matrix:
  - secure: muCE7Zrb33IDFSKhDNFilNj4tobLjtTkvQNZ/nufvEsYDXnJycVoaF5LdU7CFjKU4uo3wrnD2Q5hUn/MsHVaCcrBZVNzK1L812a/sA1gJUWD3MsDYLDeWSTu12bj5glNjk8LUk+95FUZv3Q7V+gyvzJkIuOfpGgWc9fDfARMB2tuCyXhG8BB92H3KBLoePn3iBjqvYZtr0SOoacRf9XKxoFYfERZMmYkPmtTyxql74G62dkEjRzi0/J4jw+0C+zl9yuJzJTlUJ2MAI0fCbqEXC2vSHNqLnqNqvPK64/+TmZZu/raucJBSSqSYgjqEevVILt84C5bJ1ht+78RKpzpfv4bWcZczqhPjzK5sisVE1kjakH5dtSeQRueg6HbVMKOI/qVBCWNdSmlepaw3lMmJwUFxS2z7cL1rGFxQyP/cbtgxnJBTmpdg5zYgUj4hLMAss1S0NVkAB4DbZJddq7gdF8gBYpXV1QGidkB6yjXbXeAC90YeKJXdc702864VrfCodFvOjTZTpUags3JcIyO0Zj96ozg8S37maeI+e4tbI4BeqjYZthEU4hMD8x4uaU6foytm7htdepyxfmbmJnYzO3hgrcsAaoC9Sv2DeY1Jw4DKYbpEkuq3hlLOiqPCFVIdamhYAVPAnHjlQ9HUhZJeU4Es793lj2xuN6u6kymW3c=
  - secure: MqSHt+BOB1M6QhS07bSsK/5RUAHC5ynOuZ/nIMli9z1+On/iQ7tYvvDTBqniEkNhIP81RqzutmCCHRpC8JcyALjDa2kP1hBGSPUh3xj+BouwwE5Dexk/pTGsbwJ1yPl4AcpFBVjdPeB34JXtlIc37kqLx98MWOmOPeTnOXLuwB3aOZqJn6Rv40kqkrP1NgyYqlfW15t3Jte03CCD0AeIG3E6EGT5v/ye8ANVpBjNtOL0As6Z3fxyTwm/JpM210mTl2AXW81HBZsp2oo9AizH4KiTqMXKWGY4RAGiAN7Y3BNKSQx7774/rXrNcnS8s90KUz93huixqPIFa4tdKdcGTmclaALV0wO0nBDwZOTYUg+6dVfSHKg3r+ovApwda35uDPMEvAcWpSLQBhumu6o2qhe9+L1e+UXb+UftuOBP2hpmo1TexMT0EroAMxsilVOY4SrS3MVET5ErZ73tBPDvAzrOArPnHMvHowfxIWzE1TSkPWo/s0v1d6m3V1frvmS9WCYjY/8L/ZUm9DU7am2zw/LKvT8Hj6zp8CFRgJdmZeAF33sPFWaINnt4j9cA5fKHDW4yeUwoHMaVM1K0XmRnr/gzpsNQUmSMwTeWsEZK7b1rrpTxvBBqU2wRdrmZCzCmft9XJT7n69v3vjKOvAgO2PSaXXHVT9pG98o+/tqPzkk=
